### ISSUE TITLE
Incorrect recycled view when viewtypecount > 1

### ISSUE THREAD

**Issue by tuandigital** [felipecsl/QuickReturn#16]
When I use your library for an ArrayAdapter with viewtypecount > 1. The recycled view in getView is not match with view type. I found the solution in your QuickReturnAdapter.java, just change to the following lines:

    @Override
    public int getItemViewType(final int position) {
        if (position < numColumns)
            return wrappedAdapter.getViewTypeCount();
        return wrappedAdapter.getItemViewType(position - numColumns);
    }

Could you take a look at this fix:)

Thanks,
-Tuan

**Comment by felipecsl** [comment]
Fixed via #28
