### ISSUE TITLE
TargetView show/hide option. 

### ISSUE THREAD

**Issue by subhasha1** [felipecsl/QuickReturn#31]
Hello,
Is it possible to implement hide/show of target view manually?

**Comment by mrdnote** [comment]
I did this quick and dirty like this:

        mQuickReturnTargetView = (AbsListViewScrollTarget) mQuickReturnAttacher.addTargetView(mStickyPanel, QuickReturnTargetView.POSITION_TOP, mStickyPanel.getHeight());

	public void open() {
		mQuickReturnTargetView.translateTo(0);
		mOpen = true;
	}
	
	public void close() {
		mQuickReturnTargetView.translateTo(-mStickyPanel.getHeight());
		mOpen= false;
	}

	public void toggle() {
		if (mOpen)
			close();
		else
			open();
	}

You have to make QuickReturnTargetView.translateTo() public for this to work. 

I'm sure there are better ways to do this and I'm open for suggestions!

**Comment by subhasha1** [comment]
Thanks a lot. This will help for now.
